; PlatformIO Project Configuration File
; RTOS-Based Multi-Sensor Gateway for STM32 NUCLEO-L433RC-P

[platformio]
default_envs = nucleo_l433rc_p

[env:nucleo_l433rc_p]
platform = ststm32
board = nucleo_l433rc_p
framework = stm32cube

; Build flags
build_flags =
    -DSTM32L433xx
    -DUSE_HAL_DRIVER
    -DFREERTOS
    -I Core/Inc
    -I Drivers/BSP
    -I Drivers/MPU6050
    -I Drivers/DHT11
    -I Drivers/Potentiometer
    -I Middleware/RingBuffer
    -I App/Inc
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
    -O2
    -Wall
    -Wextra

; Upload & Monitor settings
upload_protocol = stlink
monitor_speed = 115200
monitor_filters = direct, send_on_enter
